### ISSUE TITLE
Can you also generate a file named "latest.json"?

### ISSUE THREAD

**Issue by hzlzh** [ahappypie/github-trending-daily#75]
When the actions run, generate both `2020-11-02.json` and `latest.json`, so that Apps can use your API like 
`https://raw.githubusercontent.com/ahappypie/github-trending-daily/master/data/latest.json`

**Comment by ahappypie** [comment]
Appreciate the interest. I think that would be a simple addition, let me take a look.

However, just to give some background, I threw this script together to help me with my daily reading, so it has some limitations:
* Only runs on weekdays
* I merge new data manually
* Limited number of languages
* Only pulls links, not stars, etc.

If you'd like to collaborate on expanding the project I'm all for it - at some point I'd like to generate static pages through something like Next.js once new data is added. Github Pages could host both the generated pages and JSON files. That would make access to the files a lot cleaner, in my opinion.

I'm also not clear on what Github's policy about this data is. Obviously they don't provide an API so it's not something they feel is a programmatic access-type thing. I think it's a missing feature so I made this, but maybe one day they will add an endpoint.

**Comment by ahappypie** [comment]
I've confirmed that the `latest.json` file is created, and merged today's data. I will leave this open to confirm tomorrow that latest will be overwritten but I expect this is solved.

**Comment by ahappypie** [comment]
Confirmed overwrite. I am also working on static site generation on another branch, that will change how the data is accessed (for the better). Check back for that improvement soon.

**Comment by ahappypie** [comment]
I've added static site generation, now you can get the JSON data by going to `https://ahappypie.github.io/github-trending-daily/$DATE.json`. `latest.json` is also an option.
